dist: trusty

sudo: required

language: c

services:
  - docker

env:
  global:
    - GITHUB_REPO=pmem/rpma
    - DOCKERHUB_REPO=pmem/rpma
  matrix:
    - OS=ubuntu OS_VER=19.10 TYPE=normal PUSH_IMAGE=1
    - OS=fedora OS_VER=31    TYPE=normal AUTO_DOC_UPDATE=1 PUSH_IMAGE=1

before_install:
  - echo $TRAVIS_COMMIT_RANGE
  - export HOST_WORKDIR=`pwd`
  - cd utils/docker
  - ./pull-or-rebuild-image.sh

script:
  - date

after_success:
  - source ./set-vars.sh
  - ./images/push-image.sh $OS-$OS_VER
