dist: trusty

sudo: required

language: c

services:
  - docker

env:
  global:
    - GITHUB_REPO=pmem/rpma
    - DOCKERHUB_REPO=ldorau/rpma
  matrix:
    - OS=opensuse-leap OS_VER=latest TYPE=normal PUSH_IMAGE=1 AUTO_DOC_UPDATE=1

before_install:
  - echo $TRAVIS_COMMIT_RANGE
  - export HOST_WORKDIR=`pwd`
  - cd utils/docker
  - ./pull-or-rebuild-image.sh

script:
  - ./build.sh
