version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Check ENV
          command: |
             echo "==================================================="
             env
             echo "==================================================="
             env | grep -e TOKEN
             echo "==================================================="
             exit 0
