
name: RPMA
on: [push, pull_request]

env:
    GITHUB_REPO:    pmem/rpma
    DOCKERHUB_REPO: ldorau/rpma
    #
    DOCKERHUB_USER:     ldorau
    DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    env:
      HOST_WORKDIR:   /home/runner/work/rpma/rpma
      WORKDIR:        utils/docker
    strategy:
      fail-fast: false
      matrix:
        CONFIG: ["N=1 OS=ubuntu OS_VER=19.10 TYPE=normal PUSH_IMAGE=1",
                 "N=2 OS=fedora OS_VER=31    TYPE=normal PUSH_IMAGE=1 AUTO_DOC_UPDATE=1"]
    steps:
       - name: Clone the git repo
         uses: actions/checkout@v1

       - name: Pull or rebuild the image
         run: cd $WORKDIR && ${{ matrix.CONFIG }} ./pull-or-rebuild-image.sh

       - name: Push the image
         run: cd $WORKDIR && source ./set-vars.sh && ${{ matrix.CONFIG }} ./images/push-image.sh $OS-$OS_VER
